<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checklistBtn_tc</name>
   <tag></tag>
   <elementGuidId>9917c29b-62cd-4399-8252-ef656070ffb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create-account-privacy-policy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='create-account-privacy-policy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a2a3152-fc45-43ec-92e1-e5517b8b1905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-input </value>
      <webElementGuid>cb9afb49-8c1d-4c0a-816d-802c01ab0180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true}</value>
      <webElementGuid>7b193e05-cadd-4420-bc7b-deda7959335b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58be24d1-a047-4754-b37a-f11fd3e56796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1016b3da-0bb6-40bf-8646-9fadecdfaf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>create-account-privacy-policy</value>
      <webElementGuid>69a8bb77-a181-4a36-80f3-2889a9ef65d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create-account-privacy-policy</value>
      <webElementGuid>3670bdda-9306-46a1-96f1-f62e3d6162dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create-account-privacy-policy&quot;)</value>
      <webElementGuid>8ddeed37-5be7-47da-a064-35b6a5e8c975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='create-account-privacy-policy']</value>
      <webElementGuid>60101f9c-2e78-4c98-9399-48b43ffe70e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate1']/fieldset[3]/div/input</value>
      <webElementGuid>2dc282a6-53ca-4742-ae8a-6fd587c90901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/input</value>
      <webElementGuid>2236182e-cd5b-415c-9e83-e45ddd5b2e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'create-account-privacy-policy' and @name = 'create-account-privacy-policy']</value>
      <webElementGuid>f9fc56b5-3c2d-4e68-9ae5-963470661efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
