<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_firstname</name>
   <tag></tag>
   <elementGuidId>8ae23a33-2839-4853-b85f-cac34d7e4558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-pair > div.field.field-name-firstname.required.inputwrapper > div.control > #firstname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='firstname'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81965a9f-4596-4b1a-8ac3-7c1cf24e58b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>133e0ac9-ac28-4aa2-a450-01991c88ed70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>1088b89c-06b6-4a91-ba33-0f95618884e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>32a65ffb-2d30-46d0-bdca-993aa6a904a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nama Depan</value>
      <webElementGuid>c603c5fe-5230-4178-b01d-8059b6fa3913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text validationfirstname </value>
      <webElementGuid>8ec40a07-86c0-44ff-ba7f-ca8ad1db2d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{</value>
      <webElementGuid>3aefbb50-5b76-4c7b-94da-71ce40163981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>04ea36d3-7dd4-420e-a2d9-82f6437e67b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>75297083-d97c-4741-9aa2-6bf39b75559e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-validate1&quot;)/fieldset[@class=&quot;fieldset create info&quot;]/div[@class=&quot;input-pair&quot;]/div[@class=&quot;field field-name-firstname required  inputwrapper&quot;]/div[@class=&quot;control&quot;]/input[@id=&quot;firstname&quot;]</value>
      <webElementGuid>f4cc7448-4c5a-42f9-9795-f6d354d3427f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='firstname'])[3]</value>
      <webElementGuid>71bcf7ba-4c5a-471f-aa9c-157b0467b56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate1']/fieldset/div/div/div/input</value>
      <webElementGuid>e0f61a0f-9d5f-4805-89b6-06baa4d00ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>94b0f4aa-3203-47be-893c-52814f246ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'firstname' and @name = 'firstname' and @title = 'Nama Depan']</value>
      <webElementGuid>05348711-7548-470a-9e66-22f9178c34b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
