<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_lastname</name>
   <tag></tag>
   <elementGuidId>d67dee9b-5d9a-4dcf-a33f-cca24c1c4f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-pair > div.field.field-name-lastname.required.inputwrapper > div.control > #lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='lastname'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>985cb8ba-723a-45ad-9b3b-7c4981928dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58372cc0-5c4a-43eb-8fb8-fe5465972ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>3041260b-6e63-4f70-887b-64b1aa504eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>60610637-3f75-4c86-b2c6-14a2ce3e0c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nama Terakhir</value>
      <webElementGuid>cbf255c1-f0e4-493d-938e-d0556620b9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>3e7a28e9-000a-4e76-889c-14afede2b7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{</value>
      <webElementGuid>1cbcd761-d348-4282-b9ab-ac231d0880d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>26115257-71aa-4cd9-8366-297236b6f923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f8dd804-9d6c-4610-9062-169becd12b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-validate1&quot;)/fieldset[@class=&quot;fieldset create info&quot;]/div[@class=&quot;input-pair&quot;]/div[@class=&quot;field field-name-lastname required inputwrapper&quot;]/div[@class=&quot;control&quot;]/input[@id=&quot;lastname&quot;]</value>
      <webElementGuid>e4374850-aa9d-48bd-ab55-3260d0e6a6fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='lastname'])[3]</value>
      <webElementGuid>e7397094-b8d1-4d76-852c-6388785b48c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate1']/fieldset/div/div[2]/div/input</value>
      <webElementGuid>7f8aa130-ae01-424d-8767-ba3543ea4b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>35b114ce-4815-4170-bf3c-30f346a0f5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lastname' and @name = 'lastname' and @title = 'Nama Terakhir']</value>
      <webElementGuid>0f36f7bc-39c1-4bf7-962a-fe3c9d28b047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
