<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_forgotPassword</name>
   <tag></tag>
   <elementGuidId>b157a2ff-daf8-4712-95dc-d834852d90ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.remind.hidden-xs > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/fieldset/div[6]/div[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d46d2fad-a9ab-471a-b9a1-aebf880f4b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa kata sandi anda?</value>
      <webElementGuid>d33c0cdc-bf98-44aa-bb43-6ddd6c12ec8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;block block-customer-login&quot;]/div[@class=&quot;block-content&quot;]/form[@id=&quot;login-form&quot;]/fieldset[@class=&quot;fieldset login&quot;]/div[@class=&quot;actions-toolbar&quot;]/div[@class=&quot;secondary&quot;]/a[@class=&quot;action remind hidden-xs&quot;]/span[1]</value>
      <webElementGuid>1b2f5a91-9b40-4ecf-a6bf-04374f3aea90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/div[6]/div[2]/a/span</value>
      <webElementGuid>9414f846-70c6-480f-8ec5-0c067acbd285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[6]/following::span[1]</value>
      <webElementGuid>54397297-12d4-48b8-bd14-0d4d7469dbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa kata sandi anda?'])[3]/following::span[2]</value>
      <webElementGuid>bfa7242d-fcdf-4cd7-9d4f-7cfb3427041f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atau'])[1]/preceding::span[1]</value>
      <webElementGuid>390ec3b6-6f5e-4183-957e-dffc09441969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelanggan Baru'])[1]/preceding::span[2]</value>
      <webElementGuid>a8865c23-c282-47b0-8111-0d709030a7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/a/span</value>
      <webElementGuid>c1517043-3a46-458d-b563-cdd81c720e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Lupa kata sandi anda?' or . = 'Lupa kata sandi anda?')]</value>
      <webElementGuid>5a436b7a-889e-42ea-9242-0d6dc7c46936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
